#language: java
#install: mvn install -DskipTests=true -Dgpg.skip=true
#jdk:
#  - oraclejdk8
#  - oraclejdk7
#  - openjdk7
#  - openjdk6
  

install:
  - mvn install -DskipTests=true -Dgpg.skip=true
  
build_script:
  - mvn test 
